import { ReduxProvider } from '@/redux/ReduxProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthSessionProvider from '../authSessionProvider/AuthSessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Demo Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <AuthSessionProvider>
           {children}
          </AuthSessionProvider>
        </ReduxProvider>
       
        </body>
    </html>
  )
}
